@startuml
' Sensors
package sensors {
  rectangle "Plant Water Alarm" as plantwa
  rectangle "Pump Water Alarm" as pumpwa
  rectangle "Light Status" as ls
  rectangle "Soil moisture" as sm
}
' Actuators 
rectangle "Pump" as pump

'Message bus
rectangle "MQTT" as mqtt


'arrows
plantwa --> mqtt : "publishes to"
pumpwa --> mqtt : "publishes to"
ls --> mqtt : "publishes to"
sm --> mqtt : "publishes to"

rectangle "InfluxDB" as influx
rectangle "Webserver" as web

mqtt <-- influx : "read from"
mqtt <-- web : "read from"

web --> influx : "read from"

@enduml
